// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   PageCS.tt
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Navigation;
using Microsoft.Phone.Controls;
using Microsoft.Phone.Shell;
using MyToolkit.Paging;
using Newtonsoft.Json;
using WPAppStudio;
using WPAppStudio.Entities;
using WPAppStudio.Helpers;
using WPAppStudio.Ioc;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;
using PhoneKit.Framework.Support;
using PhoneKit.Framework.Core.Tile;
using WPAppStudio.Resources;
using WPAppStudio.Services;

namespace WPAppStudio.View
{
    /// <summary>
    /// Phone application page for StudyAbroad_News.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class StudyAbroad_News : PhoneApplicationPage
    {       
        /// <summary>
        /// Initializes the phone application page for StudyAbroad_News and all its components.
        /// </summary>
        public StudyAbroad_News()
        {
            InitializeComponent();        
			if (Resources.Contains("PanoramaStudyAbroad_News0AppBar"))
				PhonePage.SetApplicationBar(this, Resources["PanoramaStudyAbroad_News0AppBar"] as BindableApplicationBar);

            // register startup actions
            StartupActionManager.Instance.Register(5, ActionExecutionRule.Equals, () =>
            {
                FeedbackManager.Instance.StartFirst();
            });
            StartupActionManager.Instance.Register(10, ActionExecutionRule.Equals, () =>
            {
                FeedbackManager.Instance.StartSecond();
            });   
		}
		
        private void panoramaStudyAbroad_News_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {		
			InitializeAppBarpanoramaStudyAbroad_News(PanoramaStudyAbroad_News.SelectedItem as PanoramaItem);
        }
		
		private void InitializeAppBarpanoramaStudyAbroad_News(PanoramaItem panoramaItem)        
        {
			if (Resources.Contains(panoramaItem.Name + "AppBar"))
			{
				PhonePage.SetApplicationBar(this, Resources[panoramaItem.Name + "AppBar"] as BindableApplicationBar);            
				ApplicationBar.IsVisible = true;
            }
		    else if(ApplicationBar != null)
		        ApplicationBar.IsVisible = false;
        }
 
        /// <summary>
        /// Called when the page becomes the active page.
        /// </summary>
        /// <param name="e">Contains information about the navigation done.</param>
        protected override  void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
		
            StudyAbroad_NewsListControl.SelectedItem = null;
		
            News_NewsListControl.SelectedItem = null;
		
            WindowsPhone_NewsListControl.SelectedItem = null;
		
            Windows8_NewsListControl.SelectedItem = null;

            StartupActionManager.Instance.Fire();
		}

        private void BindableApplicationBarMenuItem_Click(object sender, EventArgs e)
        {
            NavigationService.Navigate(new Uri("/View/HelpPage.xaml", UriKind.Relative));
        }
    }
}
