// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// News_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface INews_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechNews_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareNews_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartNews_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceNews_DetailStaticControlCommand { get; }

	}
}
