// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// StudyAbroad_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IStudyAbroad_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechStudyAbroad_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechStudyAbroad_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareStudyAbroad_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareStudyAbroad_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartStudyAbroad_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartStudyAbroad_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceStudyAbroad_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceStudyAbroad_DetailStaticControlCommand { get; }

	}
}
