// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Windows8_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IWindows8_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechWindows8_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechWindows8_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareWindows8_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareWindows8_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartWindows8_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartWindows8_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceWindows8_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceWindows8_DetailStaticControlCommand { get; }

	}
}
