// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// WindowsPhone_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IWindowsPhone_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechWindowsPhone_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareWindowsPhone_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartWindowsPhone_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceWindowsPhone_DetailStaticControlCommand { get; }

	}
}
