// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Windows8_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Windows8_DetailViewModel : BindableBase, IWindows8_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Windows8_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Windows8_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechWindows8_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechWindows8_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechWindows8_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechWindows8_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechWindows8_DetailStaticControlCommand
        {
            get { return _textToSpeechWindows8_DetailStaticControlCommand = _textToSpeechWindows8_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechWindows8_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareWindows8_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareWindows8_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Summary, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareWindows8_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareWindows8_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareWindows8_DetailStaticControlCommand
        {
            get { return _shareWindows8_DetailStaticControlCommand = _shareWindows8_DetailStaticControlCommand ?? new DelegateCommand(ShareWindows8_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartWindows8_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartWindows8_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IWindows8_DetailViewModel), CreateTileInfoWindows8_DetailStaticControl());
        }
		

        private ICommand _pinToStartWindows8_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartWindows8_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartWindows8_DetailStaticControlCommand
        {
            get { return _pinToStartWindows8_DetailStaticControlCommand = _pinToStartWindows8_DetailStaticControlCommand ?? new DelegateCommand(PinToStartWindows8_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceWindows8_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceWindows8_DetailStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceWindows8_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceWindows8_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceWindows8_DetailStaticControlCommand
        {
            get { return _goToSourceWindows8_DetailStaticControlCommand = _goToSourceWindows8_DetailStaticControlCommand ?? new DelegateCommand(GoToSourceWindows8_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the Windows8_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoWindows8_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-f57c05f7-f831-4da3-9cb9-a68e3f33396b.png"
            };
            return tileInfo;
        }
    }
}
