// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of WindowsPhone_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class WindowsPhone_DetailViewModel : BindableBase, IWindowsPhone_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="WindowsPhone_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public WindowsPhone_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechWindowsPhone_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechWindowsPhone_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechWindowsPhone_DetailStaticControlCommand
        {
            get { return _textToSpeechWindowsPhone_DetailStaticControlCommand = _textToSpeechWindowsPhone_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechWindowsPhone_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareWindowsPhone_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Summary, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareWindowsPhone_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareWindowsPhone_DetailStaticControlCommand
        {
            get { return _shareWindowsPhone_DetailStaticControlCommand = _shareWindowsPhone_DetailStaticControlCommand ?? new DelegateCommand(ShareWindowsPhone_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartWindowsPhone_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IWindowsPhone_DetailViewModel), CreateTileInfoWindowsPhone_DetailStaticControl());
        }
		

        private ICommand _pinToStartWindowsPhone_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartWindowsPhone_DetailStaticControlCommand
        {
            get { return _pinToStartWindowsPhone_DetailStaticControlCommand = _pinToStartWindowsPhone_DetailStaticControlCommand ?? new DelegateCommand(PinToStartWindowsPhone_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceWindowsPhone_DetailStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceWindowsPhone_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceWindowsPhone_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceWindowsPhone_DetailStaticControlCommand
        {
            get { return _goToSourceWindowsPhone_DetailStaticControlCommand = _goToSourceWindowsPhone_DetailStaticControlCommand ?? new DelegateCommand(GoToSourceWindowsPhone_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the WindowsPhone_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoWindowsPhone_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-f57c05f7-f831-4da3-9cb9-a68e3f33396b.png"
            };
            return tileInfo;
        }
    }
}
